### ISSUE TITLE
Mixins

### ISSUE THREAD

**Issue by esromneb** [bryntum/chronograph#9]
Is BetterMixins.ts something that should/could be broken out into it's own npm module?

Seems like this would be very useful for general purpose usage

**Comment by SamuraiJack** [comment]
It could be, yes. This is the 2nd iteration of mixins implementation and I just want to collect some feedback and possibly make one more round of refactoring (the idea of using TS-transformers looks very intriguing). 

It is already good enough may be, we'll see, keeping the ticket for the future.

**Comment by canonic-epicure** [comment]
Published as https://www.npmjs.com/package/typescript-mixin-class

Finally :)

**Comment by canonic-epicure** [comment]
https://github.com/canonic-epicure/typescript-mixin-class
